version: 2


sphinx:
  configuration: docs/conf.py  # point to your conf.py file inside the docs folder

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

  jobs:
    pre_build:
      - python3 -m ford -d scr -e F90 ford.yml -o docs/api

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
