version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

formats:
  - pdf
  - epub

python:
  install:
    - requirements: requirements.txt

commands:
 - python3 -m ford -d scr -e F90 ford.yml
