version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install sphinx ford
      - python3 -m ford -d scr -e F90 ford.yml

sphinx:
  configuration: docs/conf.py


